# Generated by Django 5.2.7 on 2025-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitemap_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='pages_per_review',
            field=models.PositiveIntegerField(default=1, help_text='Number of pages to review per email'),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='review_cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to send review emails', max_length=20),
        ),
    ]
