# Generated by Django 5.2.7 on 2025-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitemap_pages_per_review_sitemap_review_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='needs_review',
            field=models.BooleanField(default=True, help_text='Whether this page needs to be reviewed'),
        ),
    ]
