# Generated by Django 5.2.7 on 2025-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_email_time',
            field=models.TimeField(blank=True, help_text="Preferred time of day to receive emails (in user's timezone)", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone (e.g., 'America/New_York', 'Europe/London')", max_length=63),
        ),
    ]
