# Generated by Django 5.2.7 on 2025-10-30 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailsent_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(help_text='Email address to receive notifications', max_length=254)),
                ('enabled', models.BooleanField(default=True, help_text='Whether to send notifications to this email')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'email_address')},
            },
        ),
    ]
