# Generated by Django 5.2.7 on 2025-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this page is still present in the sitemap'),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this sitemap is still accessible and should be processed'),
        ),
    ]
