# Generated by Django 5.2.7 on 2026-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_page_is_active_sitemap_is_active'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_profile "
                "DROP COLUMN IF EXISTS customer_id, "
                "DROP COLUMN IF EXISTS product_id, "
                "DROP COLUMN IF EXISTS subscription_id;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text="The user's Stripe customer id, if it exists", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text="The user's Stripe subscription id, if it exists", max_length=255, null=True),
        ),
    ]
