# Generated by Django 5.2.7 on 2026-02-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE
                row_record RECORD;
            BEGIN
                FOR row_record IN (
                    SELECT tablename
                    FROM pg_tables
                    WHERE schemaname = 'public'
                      AND tablename LIKE 'djstripe_%'
                ) LOOP
                    EXECUTE format(
                        'DROP TABLE IF EXISTS %I.%I CASCADE',
                        'public',
                        row_record.tablename
                    );
                END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
