# Generated by Django 5.2.7 on 2026-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260209_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text="The user's Stripe customer id, if it exists", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', help_text="The user's Stripe subscription id, if it exists", max_length=255),
        ),
    ]
